- name: Remove old docker packages
  action: "{{ansible_pkg_mgr}} name=podman,docker,docker-ce,docker-ce-cli,containerd.io,docker,docker-client,docker-client-latest,docker-common,docker-latest,docker-latest-logrotate,docker-logrotate,docker-engine state=absent update_cache=no"
- name: Remove old files and packages
  file:
    path: "/usr/bin/docker*"
    state: absent
- name: Remove old images/containers
  file:
    path: "/var/lib/docker/image"
    state: absent
