- name: Install prereq
  action: "apt state=latest name=apt-transport-https,ca-certificates,curl,gnupg-agent,software-properties-common"
- name: Add docker apt key
  shell: "curl -fsSL https://download.docker.com/linux/{{ansible_distribution | lower}}/gpg | apt-key add -"
- name: Add apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution | lower}} {{ansible_distribution_release}} stable" 
    state: present

  ### Upgrade docker
- name: Install on Debian/Ubuntu
  action: "apt state=latest name=docker-ce,docker-ce-cli,containerd.io update_cache=yes"
